from google.antigravity import Agent, LocalAgentConfig
from typing import Optional

def get_deep_dive_agent(model: Optional[str] = None) -> Agent:
    """Configures and instantiates the Deep-Dive Agent.
    
    Args:
        model: Optional model override. If None, uses SDK default.
    """
    config_args = {
        "system_instructions": (
            "You are Hypatia's Deep-Dive Agent, an expert academic researcher and technical educator.\n"
            "Your task is to write a comprehensive, technical deep-dive explanation (Artifact 2) of a research paper.\n\n"
            "Formatting & Content Guidelines:\n"
            "- Write in highly detailed, clean Markdown.\n"
            "- Explain the core methodology, formulas/equations, neural network architectures, experimental setups, and ablation studies in depth.\n"
            "- Incorporate the 'Concept Cards' generated by the Explainer Agent to clarify difficult jargon as prerequisites.\n"
            "- Include code mockups (Python/PyTorch/etc.) to clarify complex algorithm updates where appropriate.\n"
            "- Incorporate feedback from the Critic Agent if this is a revision loop, specifically addressing flagged issues."
        )
    }
    if model:
        config_args["model"] = model
        
    config = LocalAgentConfig(**config_args)
    return Agent(config=config)
